title: Julie Son-Garcia # your name (or website title) here
logo: "/images/IMG_3533.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data analyst | Healthcare | Lab Tech | 
 I love to travel, Sip on Froses, and explore <br><br>
  <a href="https://www.linkedin.com/in/julie-sg2016"> View My LinkedIn Profile </a> 
  
theme: jekyll-theme-minimal

